---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Enable EPEL repo
  ini_file:
    dest: "{{ epel_repofile_path }}"
    section: epel
    option: enabled
    value: 1
  when: epel_repofile_result.stat.exists
